os: linux
dist: focal

language: python
python:
  - "3.8"

addons:
  apt:
    update: true
    packages:
      - libxml2-dev

vm:
  create:
    name: my_custom_image_new
before_install:
  - echo "Installing dependencies..."

script:
  - echo "Running tests..."
