os: linux
dist: focal

language: python
python:
  - "3.8"

addons:
  apt:
    update: true
    packages:
      - libxml2-dev

create:
name: my_custom_name #custom identifier string, human readable
before_install:
  - echo "Installing dependencies..."

script:
  - echo "Running tests..."
