os: linux
dist: focal

language: python
python:
  - "3.8"

addons:
  apt:
    update: true
    packages:
      - libxml2-dev

vm:
  use:
    name: naruto_image
before_install:
  - echo "Installing dependencies..."

script:
  - echo "Running tests..."
